repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
        exclude: ^tests/.*\.tsv$
    -   id: trailing-whitespace
        exclude: ^tests/.*\.tsv$
-   repo: local
    hooks:
    -   id: ruff-format
        name: ruff format
        entry: poetry run ruff format
        language: system
        types: [python]
    -   id: ruff-check
        name: ruff check
        entry: poetry run ruff check
        language: system
        types: [python]
