name: TestPyPI
on:
  push:
    branches:
      - develop
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        architecture: x64
    - run: pip install nox==2024.10.9
    - run: pip install poetry==1.8.4
    - run: nox
    - run: version=$(poetry version --short) && poetry version $version.dev.$(date +%s)
    - run: poetry build
    - run: poetry config repositories.test-pypi https://test.pypi.org/legacy/
    - run: poetry publish --repository test-pypi --username=__token__ --password=${{ secrets.TEST_PYPI_TOKEN }}
